### Preamble

In [2]:
!curl -s "https://raw.githubusercontent.com/Yoonsen/Modules/master/module_update.py" > "module_update.py"

In [3]:
from module_update import update, css

In [4]:
css()

# Find similar words

Find spelling variants and OCR-errors

In [5]:
import nbtext as nb
from nbtext import sorted_wildcardsearch



Use * as wildcard, and *factor* determines size of matching words, which gives a kind of Levenshtein-effekt.

#### Look for OCR-errors

In [6]:
sorted_wildcardsearch(
    {
        'word': 'kj*lig*d',   # search pattern
        'factor':3,           # factor determines length of result as difference from pattern
        'freq_lim':50,        # lowest frequency
        'limit':50            # number of hits
        
    })

             kj*lig*d
kjærlighed      42363
kjcerlighed      4137
kjerlighed       1046
kjcrrlighed       860
kjoerlighed       406
kjølighed         384
kjærligbed        255
kjærligked        117
kjaerlighed       101
kjærliglied       100
kjcerlighcd        86
kjcrrlighcd        82
kjarlighed         73
kjwrlighed         60

#### Find inflections

In [7]:
sorted_wildcardsearch(
    {
        'word': 'barn*',    # search pattern
        'factor':2,           # factor determines length of result as difference from pattern
        'freq_lim':50,        # lowest frequency
        'limit':50            # number of hits
        
    })

           barn*
barn     7510973
barnet   2434370
barna    2410483
barnets   526760
barns     383517
barnas    271674
barndom   195602
barne-    131835
barne      28490
barnen     27716
barnlig    26706
barnene    26556
barnløs    18681
barneår    10924
barn-       8056
barnens     7595
barnet.     5541
barneog     5304
barnet,     4662
barnetB     2219
barnål      2138
barnleg     1830
barnl       1596
barnB       1370
barner      1324
barnel      1272
barnes      1231
barnsøl     1213
barnaB      1163
barna.      1155
barni       1137
barnef      1114
barnlos      986
barna,       890
barnek       774
barned       757
barnn        716
barnit       710
barnev       663
barneh       591
barnetß      534
barns-       512
barneha      480
barnhem      472
barneb       472
barndåp      463
barnat       460
barnlss      451
barnete      437
barnan       397

#### Find compounds

In [8]:
sorted_wildcardsearch(
    {
        'word': 'sitron*',    # search pattern
        'factor':6,           # factor determines length of result as difference from pattern
        'freq_lim':50,        # lowest frequency
        'limit':50            # number of hits
        
    })

               sitron*
sitron           73502
sitronsaft       64812
sitroner         14599
sitronskall      13843
sitronsyre        7600
sitronen          6345
sitronsaften      5538
sitronbåter       5167
sitron-           4797
sitrongress       4604
sitronskiver      4598
sitronmelisse     4405
sitronskive       3920
sitronene         2757
sitrongul         2723
sitrongule        2384
sitronbrus        2282
sitronjuice       2072
sitronskallet     1973
sitrongult        1701
sitronsmak        1316
sitronsaus        1177
sitronolje         982
sitrontre          977
sitrontrær         970
sitronbåt          969
sitronpepper       955
sitronvann         843
sitrontimian       833
sitronar           789
sitronkake         699
sitronsaft.        637
sitrondråper       597
sitrondrops        585
sitronsaft,        584
sitronskivene      578
sitronkrem         574
sitrontreet        519
sitrontrærne       478
sitrongresset      460
sitronskal         446
sitronpai          444
sitronpresse       437
sitronskiven       425
sitronaktig        409
sitronfromasj      386
sitrontwist        382
sitronverbena      372
sitronsyren        357
sitronduft         354